// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MultipleDetailViews {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("SecondDetailView")]
	public partial class SecondDetailView {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UINavigationBar __mt_navigationBar;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("navigationBar")]
		private MonoTouch.UIKit.UINavigationBar navigationBar {
			get {
				this.__mt_navigationBar = ((MonoTouch.UIKit.UINavigationBar)(this.GetNativeField("navigationBar")));
				return this.__mt_navigationBar;
			}
			set {
				this.__mt_navigationBar = value;
				this.SetNativeField("navigationBar", value);
			}
		}
	}
}
